my_car:
# controls the rear two tires based on individual motors
  # Publish all joint states -----------------------------------
  joint_state_controller:
    # 关节状态控制器，它的主要功能是将机器人的关节状态信息（如关节的位置、速度、作用力等）收集起来并进行发布
    type: joint_state_controller/JointStateController
    # 每秒 50 次的频率发布关节状态信息
    publish_rate: 50  
  back_right_wheel_velocity_controller:
    # 速度控制器，用于控制关节的旋转速度
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  back_left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_right_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_wheel_joint
    pid: {p: 4.0, i: 2.0, d: 1.0}    
  front_left_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_wheel_joint
    pid: {p: 4.0, i: 2.0, d: 1.0}

  gazebo_ros_control:
    #在gazebo中重新分配驱动轮的pid
    pid_gains:
      back_right_wheel:
        p: 100.0
        i: 0.5
        d: 0.0
      back_left_wheel:
        p: 100.0
        i: 0.5
        d: 0.0